# Unique project key in SonarQube
sonar.projectKey=NitroStream
sonar.projectName=NitroStream

# Path to source code
sonar.sources=.

# Exclusions (Don't analyze virtual envs, static assets, media, or DBs)
sonar.exclusions=**/venv/**, **/media/**, **/static/**, **/*.sqlite3, **/.git/**

# Encoding & Language
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11