# Generated by Django 5.2.16 on 2026-08-15 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
