# Generated by Django 5.2.16 on 2026-08-15 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0002_folder_is_shared_folder_share_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='share_mode',
            field=models.CharField(choices=[('private', 'Private'), ('restricted', 'Restricted'), ('link', 'Anyone with Link')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='folder',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='share_mode',
            field=models.CharField(choices=[('private', 'Private'), ('restricted', 'Restricted'), ('link', 'Anyone with Link')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
