# Generated by Django 5.2.16 on 2026-08-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0003_folder_share_mode_folder_shared_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='hover_preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/%Y/%m/%d/'),
        ),
    ]
